config/routes.rb
Cloud1::Application.routes.draw do

  resources :order_items, only: [:create, :update, :destroy]

  
  get 'carts', to: 'carts#show'

  resources :line_items

  resources :products

  resources :product_uoms

  resources :product_types

  root to: 'line_items#index'

end

app/models/product_uom.rb
class ProductUom < ActiveRecord::Base
  attr_accessible :description, :uom
end

app/controllers/product_uoms_controller.rb
class ProductUomsController < ApplicationController
  # GET /product_uoms
  # GET /product_uoms.json
  def index
    @product_uoms = ProductUom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_uoms }
    end
  end

  # GET /product_uoms/1
  # GET /product_uoms/1.json
  def show
    @product_uom = ProductUom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_uom }
    end
  end

  # GET /product_uoms/new
  # GET /product_uoms/new.json
  def new
    @product_uom = ProductUom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product_uom }
    end
  end

  # GET /product_uoms/1/edit
  def edit
    @product_uom = ProductUom.find(params[:id])
  end

  # POST /product_uoms
  # POST /product_uoms.json
  def create
    @product_uom = ProductUom.new(params[:product_uom])

    respond_to do |format|
      if @product_uom.save
        format.html { redirect_to @product_uom, notice: 'Product uom was successfully created.' }
        format.json { render json: @product_uom, status: :created, location: @product_uom }
      else
        format.html { render action: "new" }
        format.json { render json: @product_uom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /product_uoms/1
  # PUT /product_uoms/1.json
  def update
    @product_uom = ProductUom.find(params[:id])

    respond_to do |format|
      if @product_uom.update_attributes(params[:product_uom])
        format.html { redirect_to @product_uom, notice: 'Product uom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_uom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_uoms/1
  # DELETE /product_uoms/1.json
  def destroy
    @product_uom = ProductUom.find(params[:id])
    @product_uom.destroy

    respond_to do |format|
      format.html { redirect_to product_uoms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/product_uoms_helper.rb
module ProductUomsHelper
end

app/views/product_uoms/_form.html.erb
<%= form_for(@product_uom) do |f| %>
  <% if @product_uom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_uom.errors.count, "error") %> prohibited this product_uom from being saved:</h2>

      <ul>
      <% @product_uom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :uom %><br />
    <%= f.text_field :uom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_uoms/edit.html.erb
<h1>Editing product_uom</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_uom %> |
<%= link_to 'Back', product_uoms_path %>

app/views/product_uoms/index.html.erb
<h1>Listing product_uoms</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Uom</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @product_uoms.each do |product_uom| %>
  <tr>
    <td><%= product_uom.description %></td>
    <td><%= product_uom.uom %></td>
    <td><%= link_to 'Show', product_uom %></td>
    <td><%= link_to 'Edit', edit_product_uom_path(product_uom) %></td>
    <td><%= link_to 'Destroy', product_uom, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product uom', new_product_uom_path %>

app/views/product_uoms/new.html.erb
<h1>New product_uom</h1>

<%= render 'form' %>

<%= link_to 'Back', product_uoms_path %>

app/views/product_uoms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @product_uom.description %>
</p>

<p>
  <b>Uom:</b>
  <%= @product_uom.uom %>
</p>

<%= link_to 'New', new_product_uom_path %> |
<%= link_to 'Edit', edit_product_uom_path(@product_uom) %> |
<%= link_to 'Back', product_uoms_path %>