config/routes.rb
Cloud1::Application.routes.draw do

  resources :order_items, only: [:create, :update, :destroy]

  
  get 'carts', to: 'carts#show'

  resources :line_items

  resources :products

  resources :product_uoms

  resources :product_types

  root to: 'line_items#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_type
  belongs_to :product_uom

  has_many :alternatives, through: :product_alternatives, source: :master_product
  has_many :product_alternatives, foreign_key: 'similar_product_id'
  has_many :line_items

  
  accepts_nested_attributes_for :product_alternatives, :reject_if => proc { |attributes| attributes['master_product_id'].blank? }



  attr_accessible :description, :part_number, :sanitized_part_number, :product_type_id, :product_uom_id, 
  				  :product_alternatives_attributes

validates_associated :product_type, :product_uom

  validate :description, presence: true
  validate :sanitize_part_number, uniqueness: true, if: :part_number_present?

  before_validation :sanitize_part_number


def pn_with_description

self.part_number.nil? ? self.description : "(#{self.part_number}) #{self.description}"
end

  private

  def part_number_present?
  	!self.part_number.nil?
  end


  def sanitize_part_number
  	!self.part_number.nil? ? self.sanitized_part_number = self.part_number.gsub(/[^0-9a-z ]/i, '') : self.sanitized_part_number = nil
  end

end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  attr_accessible :description
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @master_pn = @product.product_alternatives.build

    puts ">>>>>>>>>#{@master_pn.inspect}"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_type %><br />
    <%= f.collection_select :product_type_id, ProductType.all, :id, :description %>
  </div>
  <div class="field">
    <%= f.label :product_uom %><br />
    <%= f.collection_select :product_uom_id, ProductUom.all, :id, :uom %>
  </div>
  <div class="field">
    <%= f.label :part_number %><br />
    <%= f.text_field :part_number %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

<%= f.fields_for :product_alternatives do |master_pn| %>
  <div class="field">
<%= master_pn.label :master_product_id %><br />
<%= master_pn.collection_select :master_product_id, Product.all, :id, :pn_with_description, {include_blank: true} %>
</div>
<% end %>





  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>
<h3><%= link_to 'Product Types', product_types_path %> &bull; 
    <%= link_to 'Product UOM', product_uoms_path %> &bull; 
    <%= link_to 'Line  Items', line_items_path %> 
</h3>

<table>
  <tr>
    <th>Product type</th>
    <th>Product uom</th>
    <th>Part number</th>
    <th>Description</th>
    <th>Alternative to</th>    
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
   <td><%= product.product_type.description %></td>
    <td><%= product.product_uom.uom %></td>
    <td><%= product.part_number %></td>
    <td><%= product.description %></td>
    <td>
    <% if product.alternatives.any? %>
        <% product.product_alternatives.each do |alt| %>
            <li><%= alt.master_product.pn_with_description rescue nil %></li>
        <% end %>
    <% end %>
    </td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>
<p>
  <b>Part number:</b>
  <%= @product.part_number %>
</p>

<p>
  <b>Sanitized part number:</b>
  <%= @product.sanitized_part_number %>
</p>
<p>
  <b>Product type:</b>
  <%= @product.product_type.description %>
</p>

<p>
  <b>Product uom:</b>
  <%= @product.product_uom.uom %>
</p>





<%= link_to 'New', new_product_path %> |
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>