config/routes.rb
Cloud1::Application.routes.draw do

  resources :order_items, only: [:create, :update, :destroy]

  
  get 'carts', to: 'carts#show'

  resources :line_items

  resources :products

  resources :product_uoms

  resources :product_types

  root to: 'line_items#index'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :condition
  has_many :order_items

  default_scope { where('quantity > 0')}

  validates_associated :product, :condition
  validates :quantity, presence: true
  validates :stock_address, presence: true
  validates :product_id, presence: true
  validates :condition_id, presence: true

  attr_accessible :quantity, :batch_number, :exp_date, :remarks, :serial_number, 
  				  :stock_address, :product_id, :condition_id
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
    @order_item = current_order.order_items.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(params[:line_item])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %><br />
    <%= f.collection_select :product_id, Product.all, :id, :pn_with_description %> [ <%= link_to 'New Product', new_product_path, class: 'popup' %> ]
  </div>
    <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :condition %><br />
    <%= f.collection_select :condition_id, Condition.all, :id, :description %>
  </div>
  <div class="field">
    <%= f.label :exp_date %><br />
    <%= f.date_select :exp_date %>
  </div>
  <div class="field">
    <%= f.label :serial_number %><br />
    <%= f.text_field :serial_number %>
  </div>
  <div class="field">
    <%= f.label :batch_number %><br />
    <%= f.text_field :batch_number %>
  </div>
  <div class="field">
    <%= f.label :stock_address %><br />
    <%= f.text_field :stock_address %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br />
    <%= f.text_area :remarks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Condition</th>
    <th>Quantity</th>
    <th>Exp date</th>
    <th>Serial number</th>
    <th>Batch number</th>
    <th>Stock address</th>
    <th>Remarks</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product.pn_with_description %></td>
    <td><%= line_item.condition.description %></td>
    <td><%= line_item.quantity %></td>
    <td><%= line_item.exp_date %></td>
    <td><%= line_item.serial_number %></td>
    <td><%= line_item.batch_number %></td>
    <td><%= line_item.stock_address %></td>
    <td><%= line_item.remarks %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @line_item.product.pn_with_description %>
</p>

<p>
  <b>Condition:</b>
  <%= @line_item.condition.description %>
</p>

<p>
  <b>Exp date:</b>
  <%= @line_item.exp_date %>
</p>

<p>
  <b>Serial number:</b>
  <%= @line_item.serial_number %>
</p>

<p>
  <b>Batch number:</b>
  <%= @line_item.batch_number %>
</p>

<p>
  <b>Stock address:</b>
  <%= @line_item.stock_address %>
</p>

<p>
  <b>Remarks:</b>
  <%= @line_item.remarks %>
</p>

<%= link_to 'New', new_line_item_path %> |
<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>